// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgvomypqdouqvrezronm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRndm9teXBxZG91cXZyZXpyb25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjEyOTAsImV4cCI6MjA2NDU5NzI5MH0.WzDxnZI2mf7D7Fj9ZL-hGcEHT0v87BssQAPOcveQro4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);